# Site settings
title: owiber.com
tagline: i like the color pink
email: oliver@owiber.com
description: > # this means to ignore newlines until "baseurl:"
  an oliver wong blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.owiber.com" # the base hostname & protocol for your site
twitter_username: owiber
github_username:  owiber

timezone: America/Chicago
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: /page/:num/

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Oliver Wong
  url: https://twitter.com/owiber
  email: oliver@owiber.com

gems:
  - jemoji
  - jekyll-paginate
